spring.application.name=SWP_Hackathon
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SWP_Hackathon;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# --- CẤU HÌNH BẢO MẬT JWT ---
# Khóa bí mật (BẮT BUỘC dài hơn 32 ký tự để thuật toán HS256 hoạt động)
app.jwt.secret=dfguIUJY^&**hv7uhjuvsfb&**&YJHVf78qwebihad87@
# Thời gian sống của Access Token (Ví dụ này là 1 Ngày = 1000 * 60 * 60 * 24 ms)
app.jwt.accessExpirationMs=86400000
# Thời gian sống của Refresh Token (Ví dụ này là 30 Ngày)
app.jwt.refreshExpirationMs=2592000000

# Frontend (React) - used in verification email links
app.frontend-url=http://localhost:5174
app.verification.expiration-hours=24

# CORS
app.cors.allowed-origins=http://localhost:5174,http://localhost:3000,http://localhost:8080

# Mail (Gmail SMTP example - fill in credentials to send real emails)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saitama0102huy@gmail.com
spring.mail.password=vagk ikzh ejbs uypw


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# When true, log verification link to console if mail is not configured
app.mail.dev-log-link=true
spring.mail.properties.mail.debug=true

# Cloudinary
cloudinary.cloud-name=dixwy8wdk
cloudinary.api-key=272984154411446
cloudinary.api-secret=udb9PC9yIQIACNjaHG1wYtXS6Eg
server.tomcat.max-http-form-post-size=60MB
# Giới hạn dung lượng mỗi file
spring.servlet.multipart.max-file-size=60MB
# Giới hạn dung lượng tổng của một request
spring.servlet.multipart.max-request-size=100MB
# File nhỏ hơn 2MB sẽ lưu trên RAM, lớn hơn sẽ ghi tạm ra ổ đĩa (tối ưu bộ nhớ)
spring.servlet.multipart.file-size-threshold=2MB


# GitHub
github.api.base-url=https://api.github.com
github.api.token=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


github.client-id=Ov23liIyhyJfiTCS9PBP
github.client-secret=02fdf06424ed28f2678b1ab02cfff6366e31f866
github.redirect-uri=http://localhost:8080/api/github/oauth/callback
github.oauth.state-secret=d8c9d5b2d8e2f1f9c6a1e4b8f3d7a9e5

#OAUTH 2
spring.security.oauth2.client.registration.google.client-id=86966911986-fo56a76rqg5va71v1f7pg9av6do8c52q.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile