package com.hackathon.entity.enums;

public enum AuditAction {
    CREATE_EVENT,
    UPDATE_EVENT,
    DELETE_EVENT,
    CANCELLD_EVENT,
    CREATE_TEAM,
    UPDATE_ROUND,
    UPDATE_CRITERIA,
    UPDATE_TEAM,
    DELETE_TEAM,
    CREATE_CRITERIA,
    DELETE_CRITERIA,
    SUBMIT_PROJECT,
    LOGIN,
    LOGOUT,
    APPROVE_REGISTRATION,
    REJECT_REGISTRATION,
    DISQUALIFY_TEAM
}
