package com.hackathon.entity.enums;

public enum NotificationType {
    TEAM_INVITATION,
    TEAM_ACCEPTED,
    TEAM_REJECTED,

    TEAM_REGISTRATION_SUBMITTED,   // team gửi đơn
    TEAM_REGISTRATION_APPROVED,
    TEAM_REGISTRATION_REJECTED,

    LEADER_TRANSFER_REQUEST,
    SUBMISSION_RECEIVED,
    SUBMISSION_SCORED,

    JUDGE_ASSIGNED,
    MENTOR_ASSIGNED,

    SYSTEM_ANNOUNCEMENT
}
