package com.hackathon.entity.enums;

public enum NotificationType {
    TEAM_INVITATION,
    TEAM_ACCEPTED,
    TEAM_REJECTED,

    TEAM_REGISTRATION_SUBMITTED,   // team gửi đơn
    TEAM_REGISTRATION_APPROVED,
    TEAM_REGISTRATION_REJECTED,

    DISQUALIFY_TEAM,

    ASSIGNED_CATEGORY,

    CANCELLED_EVENT,

    LEADER_TRANSFER_REQUEST,
    SUBMISSION_SCORED,
    SUBMISSION_REVIEW,

    JUDGE_ASSIGNED,
    MENTOR_ASSIGNED,

    RANKING_DRAFT,
    RANKING_OFFICIAL


}
